name = "mikosch"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
title = "Mikosch Universal"
tags = ["portfolio", "blog", "studio", "storytelling", "clean"]
min_version = "0.80.0"
